export const NOTIFICATION_SERVICE = "NOTIFICATION_SERVICE";
export const NOTIFICATION_REPOSITORY = "NOTIFICATION_REPOSITORY";
export const USER_NOTIFICATION_TARGETS = "USER_NOTIFICATION_TARGETS";
export const EMAIL_CHANNEL = "EMAIL_CHANNEL";
export const PUSH_CHANNEL = "PUSH_CHANNEL";
export const SMS_CHANNEL = "SMS_CHANNEL";
