export enum NotificationType {
  FOLLOW = "FOLLOW",
  MESSAGE = "MESSAGE",
  REACTION = "REACTION",
  EVENT = "EVENT",
  EVENT_REMINDER = "EVENT_REMINDER",
  SYSTEM = "SYSTEM",
  UPDATES = "UPDATES",
  /** Códigos OTP / magic link — sempre opt-in e preferências de canal */
  VERIFICATION = "VERIFICATION",
  WELCOME = "WELCOME",
  BOOKING_INQUIRY = "BOOKING_INQUIRY",
  BOOKING_NEGOTIATION = "BOOKING_NEGOTIATION",
  BOOKING_DATES_CONFIRMED = "BOOKING_DATES_CONFIRMED",
  BOOKING_CONFIRMED = "BOOKING_CONFIRMED",
  BOOKING_DECLINED = "BOOKING_DECLINED",
  BOOKING_CANCELLED = "BOOKING_CANCELLED",
  EVENT_PUBLISHED = "EVENT_PUBLISHED",
}